kind: ConfigMap
apiVersion: v1
metadata:
  name: time-v2-cm-fs-var~name~
data:
  config-1.yaml: |
    logs: info # "debug" | "info" | "error"
    secret_key_path: secret/super-secret-1 # path to file that contains secret
    format: "ddd, MMM Do YY, h:mm:ssa zz" # moment format of the time to use

  config-2.yaml: |
    logs: debug
    secret_key_path: secret/super-secret-2
    format: "MMM-DD-YY h:mm:ssa Z" # moment format of the time to use
