apiVersion: v1
kind: Pod
metadata:
  name: time-v2-var~name~
  labels:
    version: v2
    service: atomi.core.time-var~name~
  annotations:
    created-by: var~name~
spec:
  containers:
  - name: api
    image: "kirinnee/time-v2:0.1.0"
    tty: true
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    env:
    - name: ENV
      valueFrom:
        configMapKeyRef:
          name: time-v2-cm-var~name~
          key: environment
    - name: CONFIG_PATH
      valueFrom:
        configMapKeyRef:
          name: time-v2-cm-var~name~
          key: path_to_my_config
    ports:
    - containerPort: 3000
      name:  http
    volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
      - name: my-secrets
        mountPath: "/secrets"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: time-v2-cm-fs-var~name~
    - name: my-secrets
      secret:
        secretName: time-v2-secret-var~name~

  restartPolicy: Always
