kind: ConfigMap
apiVersion: v1
metadata:
  name: time-v2-cm-fs-var~name~
data:
  config-1.yaml: |
    logs: debug
    secret_key_path: secret_file.txt
    format: "ddd, MMM Do YY, h:mm:ssa zz"
  config-2.yaml: |
    logs: debug
    secret_key_path: secret_file.txt
    format: "MMM/DD/YY h:mm:ssa Z"
