apiVersion: v1
kind: Service
metadata:
  name: time-v2-var~name~
  labels:
    version: v2
    service: atomi.core.time-var~name~
  annotations:
    created-by: var~name~
spec:
  selector:
    version: v2
    service: atomi.core.time-var~name~
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
